# main
pool:
  vmImage: windows-2022

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install test'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
 
- task: PublishTestResults@2
  inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'
      mergeTestResults: true

- task: PublishBuildArtifacts@1
  inputs:
      ArtifactName: 'Extent-Reports'
      PathToPublish: './target/Extent-Reports'

- script: 'ls -R $(System.DefaultWorkingDirectory)'
  displayName: 'List Working Directory Contents'
  continueOnError: true # Continue even if the ls command fails

- task: PublishBuildArtifacts@1
  inputs:
      ArtifactName: 'Maven-Logs'
      PathToPublish: '$(System.DefaultWorkingDirectory)'
      publishLocation: 'Container'
  condition: succeededOrFailed()

